#!/usr/bin/env bash
# Step-0 readiness check for a clickhouse-debug session. Run it FIRST, from inside
# the version-matched ClickHouse source checkout:
#
#   source ./.chenv && ./preflight.sh
#
# It confirms, in one shot, what used to be manual prose: that you're in a CH
# source tree, that the endpoints answer, that the source version matches the live
# server (line numbers depend on this), and roughly how big the fleet is (so
# fan-out caps can be sized). All cluster reads go through chq.sh, so the
# agent-query-safety caps and CH_REPLAY_DIR apply here too.
#
# NOT -e: we want to run every check and summarize, not abort on the first miss.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHQ="$SCRIPT_DIR/chq.sh"

warns=()        # non-fatal: reduced depth
blockers=()     # the agent should fix these before drilling

# --- 1. Source tree + version --------------------------------------------------
src_ver=""
verfile="cmake/autogenerated_versions.txt"
if [ -f "$verfile" ]; then
  src_ver="$(sed -n 's/.*VERSION_STRING \([0-9][0-9.]*\).*/\1/p' "$verfile" | head -n1)"
  echo "preflight: source tree     PASS  v${src_ver:-?}  ($verfile)"
elif src_ver="$(git describe --tags 2>/dev/null)"; then
  echo "preflight: source tree     PASS  $src_ver  (git describe)"
else
  echo "preflight: source tree     WARN  not a CH source tree — source confirmation unavailable"
  warns+=("not in a CH source tree")
fi

# --- 2. Endpoints --------------------------------------------------------------
if [ -n "${CH_URL:-}" ]; then
  if printf '%s' "$(curl -sk -m 5 "$CH_URL/ping" 2>/dev/null)" | grep -q "Ok."; then
    echo "preflight: ClickHouse ping PASS  $CH_URL"
  else
    echo "preflight: ClickHouse ping WARN  $CH_URL did not return 'Ok.'"
    blockers+=("ClickHouse $CH_URL unreachable")
  fi
else
  echo "preflight: ClickHouse ping FAIL  CH_URL is not set"
  blockers+=("CH_URL not set")
fi

if [ -n "${PROM:-}" ]; then
  ph="$(curl -sk -m 5 "$PROM/-/healthy" 2>/dev/null)"
  if [ -z "$ph" ]; then ph="$(curl -sk -m 5 "$PROM/api/v1/query?query=1" 2>/dev/null)"; fi
  if [ -n "$ph" ]; then
    echo "preflight: Prometheus      PASS  $PROM"
  else
    echo "preflight: Prometheus      WARN  $PROM did not answer (outside view limited)"
    warns+=("Prometheus unreachable")
  fi
else
  echo "preflight: Prometheus      WARN  PROM not set (outside view unavailable)"
  warns+=("PROM not set")
fi

# --- 3. Version match (automated) ---------------------------------------------
# Only meaningful if both the source version and a live endpoint are available.
if [ -n "${CH_URL:-}" ] || [ -n "${CH_REPLAY_DIR:-}" ]; then
  live_ver="$("$CHQ" "SELECT version()" 2>/dev/null | tail -n1)"
  norm() { printf '%s' "$1" | grep -oE '^[0-9]+\.[0-9]+\.[0-9]+' | head -n1; }
  if [ -n "$src_ver" ] && [ -n "$live_ver" ]; then
    if [ "$(norm "$src_ver")" = "$(norm "$live_ver")" ]; then
      echo "preflight: version match   PASS  source $src_ver == live $live_ver"
    else
      echo "preflight: version match   WARN  source $src_ver vs live $live_ver — line numbers may differ"
      warns+=("source/live version mismatch")
    fi
  elif [ -z "$live_ver" ]; then
    echo "preflight: version match   WARN  could not read live version()"
    warns+=("live version unknown")
  fi
fi

# --- 4. Topology (best-effort) -------------------------------------------------
clusters="$("$CHQ" "SELECT cluster, count() AS n FROM system.clusters GROUP BY cluster ORDER BY n DESC" 2>/dev/null | tail -n +2)"
if [ -n "$clusters" ]; then
  summary="$(printf '%s' "$clusters" | awk -F'\t' '{printf "%s(%s) ", $1, $2}')"
  echo "preflight: clusters        $(printf '%s' "$clusters" | wc -l | tr -d ' ') found: $summary"
else
  echo "preflight: clusters        WARN  could not enumerate system.clusters"
  warns+=("topology unknown")
fi

# --- 5. Companion reminder (model-side check) ---------------------------------
echo "preflight: companions      check your available skills for clickhouse-best-practices, altinity-expert-clickhouse-overview, altinity-profiler-clickhouse — and report any missing (it reduces depth)."

# --- Summary -------------------------------------------------------------------
if [ "${#blockers[@]}" -gt 0 ]; then
  echo "STATUS: BLOCKED: $(IFS='; '; echo "${blockers[*]}")"
elif [ "${#warns[@]}" -gt 0 ]; then
  echo "STATUS: READY (with warnings: $(IFS='; '; echo "${warns[*]}"))"
else
  echo "STATUS: READY"
fi

# Exit non-zero ONLY when CH_URL is missing (the one thing that stops every probe).
if [ -z "${CH_URL:-}" ]; then exit 2; fi
exit 0
