#!/usr/bin/env bash
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$HERE/assert.sh"
. "$HERE/../_fixture.sh"
PRE="$HERE/../preflight.sh"
tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT

# A fake CH source tree with a known version.
mkdir -p "$tmp/src/cmake"
cat > "$tmp/src/cmake/autogenerated_versions.txt" <<'EOF'
SET(VERSION_REVISION 54487)
SET(VERSION_MAJOR 24)
SET(VERSION_MINOR 3)
SET(VERSION_PATCH 1)
SET(VERSION_STRING 24.3.1.2672)
EOF

# Seed a chq replay fixture for SELECT version() that matches the source version.
mkdir -p "$tmp/fx"
vkey="$(_fixture_key chq "SELECT version()")"
printf 'version()\n24.3.1.2672\n' > "$tmp/fx/$vkey.tsv"

# Stub curl so /ping and Prometheus health "succeed" without a network.
mkdir -p "$tmp/bin"
cat > "$tmp/bin/curl" <<'STUB'
#!/usr/bin/env bash
printf 'Ok.\n'
STUB
chmod +x "$tmp/bin/curl"

# Run preflight from inside the fake source tree, in replay mode.
out="$(cd "$tmp/src" && PATH="$tmp/bin:$PATH" \
  CH_REPLAY_DIR="$tmp/fx" CH_URL="http://node:8123" PROM="http://prom:9090" \
  bash "$PRE" 2>&1)"; rc=$?

assert_rc "exits 0 when CH_URL is set" 0 "$rc"
assert_contains "reports source version" "$out" "24.3.1.2672"
assert_contains "version match passes" "$out" "version match"
assert_contains "emits a STATUS line" "$out" "STATUS:"

# Missing CH_URL is the one fatal case.
out2="$(cd "$tmp/src" && PATH="$tmp/bin:$PATH" CH_REPLAY_DIR="$tmp/fx" \
  bash "$PRE" 2>&1)"; rc2=$?
assert_rc "exits 2 when CH_URL unset" 2 "$rc2"

finish "preflight.test.sh"
