#!/usr/bin/env bash
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$HERE/assert.sh"
. "$HERE/../_fixture.sh"
PRE="$HERE/../preflight.sh"
tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT

# A fake CH source tree with a known version.
mkdir -p "$tmp/src/cmake"
cat > "$tmp/src/cmake/autogenerated_versions.txt" <<'EOF'
SET(VERSION_REVISION 54487)
SET(VERSION_MAJOR 24)
SET(VERSION_MINOR 3)
SET(VERSION_PATCH 1)
SET(VERSION_STRING 24.3.1.2672)
EOF

# Seed a chq replay fixture for SELECT version() that matches the source version.
mkdir -p "$tmp/fx"
vkey="$(_fixture_key chq "SELECT version()")"
printf 'version()\n24.3.1.2672\n' > "$tmp/fx/$vkey.tsv"

# Stub curl so /ping and Prometheus health "succeed" without a network.
mkdir -p "$tmp/bin"
cat > "$tmp/bin/curl" <<'STUB'
#!/usr/bin/env bash
printf 'Ok.\n'
STUB
chmod +x "$tmp/bin/curl"

# Run preflight from inside the fake source tree, in replay mode.
out="$(cd "$tmp/src" && PATH="$tmp/bin:$PATH" \
  CH_REPLAY_DIR="$tmp/fx" CH_URL="http://node:8123" PROM="http://prom:9090" \
  bash "$PRE" 2>&1)"; rc=$?

assert_rc "exits 0 when CH_URL is set" 0 "$rc"
assert_contains "reports source version" "$out" "24.3.1.2672"
assert_contains "version match passes" "$out" "version match"
assert_contains "emits a STATUS line" "$out" "STATUS:"

# Missing CH_URL is the one fatal case.
out2="$(cd "$tmp/src" && PATH="$tmp/bin:$PATH" CH_REPLAY_DIR="$tmp/fx" \
  bash "$PRE" 2>&1)"; rc2=$?
assert_rc "exits 2 when CH_URL unset" 2 "$rc2"

# --- Fleet version spread: uniform fleet does not warn -------------------------
ckey="$(_fixture_key chq "SELECT cluster, count() AS n FROM system.clusters GROUP BY cluster ORDER BY n DESC")"
printf 'cluster\tn\nmain\t3\n' > "$tmp/fx/$ckey.tsv"
skey="$(_fixture_key chq "SELECT hostName() AS node, version() AS ver FROM clusterAllReplicas(main, system.one)")"
printf 'node\tver\nch-01\t24.3.1.2672\nch-02\t24.3.1.2672\nch-03\t24.3.1.2672\n' > "$tmp/fx/$skey.tsv"

out3="$(cd "$tmp/src" && PATH="$tmp/bin:$PATH" \
  CH_REPLAY_DIR="$tmp/fx" CH_URL="http://node:8123" PROM="http://prom:9090" \
  bash "$PRE" 2>&1)"
assert_contains "uniform fleet: version spread PASS" "$out3" "version spread  PASS"
assert_contains "uniform fleet: does not warn" "$out3" "STATUS: READY"
assert_not_contains "uniform fleet: should not report mixed versions" "$out3" "mixed versions"

# --- Fleet version spread: mixed versions across the fleet WARNs ---------------
printf 'node\tver\nch-01\t24.3.1.2672\nch-02\t24.8.4.13\nch-03\t25.1.4.53\n' > "$tmp/fx/$skey.tsv"
out4="$(cd "$tmp/src" && PATH="$tmp/bin:$PATH" \
  CH_REPLAY_DIR="$tmp/fx" CH_URL="http://node:8123" PROM="http://prom:9090" \
  bash "$PRE" 2>&1)"
assert_contains "mixed fleet: version spread WARN" "$out4" "version spread  WARN"
assert_contains "mixed fleet: names the divergent versions" "$out4" "24.8.4.13"
assert_contains "mixed fleet: surfaces as a warning in the summary" "$out4" "mixed versions on cluster main"
assert_contains "mixed fleet: overall status still READY (non-fatal)" "$out4" "STATUS: READY (with warnings"

# --- Source-tree detection must not false-PASS on a non-ClickHouse git repo ----
# `git describe --tags` succeeds in ANY tagged repo. Run from, say, this skill's
# own repo it used to report "source tree PASS v0.7.1-…", which claims source
# confirmation is available when it is not — and, since v0.8.0, invites the
# docs->git cross-version pattern to run `git tag`/`git grep` in the wrong tree.
mkdir -p "$tmp/notch"
(cd "$tmp/notch" && git init -q . && git config user.email t@t && git config user.name t \
  && echo x > f && git add f && git commit -qm init && git tag v0.7.1) >/dev/null 2>&1

out5="$(cd "$tmp/notch" && PATH="$tmp/bin:$PATH" \
  CH_REPLAY_DIR="$tmp/fx" CH_URL="http://node:8123" \
  bash "$PRE" 2>&1)"
assert_not_contains "tagged non-CH repo does not report source tree PASS" \
  "$out5" "source tree     PASS"
assert_contains "tagged non-CH repo warns instead" "$out5" "not a CH source tree"

# A tree with the CH source markers but no autogenerated_versions.txt (e.g. a
# shallow checkout) should still be recognised, falling back to git describe.
mkdir -p "$tmp/chsrc/src/Storages/MergeTree" "$tmp/chsrc/src/Common" "$tmp/chsrc/programs"
touch "$tmp/chsrc/src/Common/ErrorCodes.cpp"
(cd "$tmp/chsrc" && git init -q . && git config user.email t@t && git config user.name t \
  && git add -A && git commit -qm init && git tag v24.3.1.2672) >/dev/null 2>&1

out6="$(cd "$tmp/chsrc" && PATH="$tmp/bin:$PATH" \
  CH_REPLAY_DIR="$tmp/fx" CH_URL="http://node:8123" \
  bash "$PRE" 2>&1)"
assert_contains "CH-shaped tree without version file still PASSes" \
  "$out6" "source tree     PASS"

# Release tags drive the docs->git cross-version confirmation, so their absence
# must be reported rather than discovered mid-incident.
assert_contains "reports release-tag availability" "$out6" "release tags"

finish "preflight.test.sh"
